---
title: "Subproject template"
author: "F. Delogu"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    toc_collapsed: true
---

```{r echo=eval_debug, eval=T}
#ls()
```

## Description

`r pid`: `r des`

## Info
**Extended metadata:** `r ext`

**People:** `r peo`

**Responsible:** `r res``

**Comments:** `r com``

## Info status 

```{r echo=eval_debug, eval=T}
missing_info(project = pid)
```

## Metadata summary

```{r warning=F, echo=eval_debug, eval=T}
summarise_metadata(data_table = mfd_db_subproject) %>%
  kable(align="r", digits=2)
```

## Metadata status
```{r echo=eval_debug, eval=T}
#ooe_text(data_table = mfd_db_subproject)
```

```{r echo=eval_debug, eval=T}
missing_meta <- missing_metadata(data_table = mfd_db_subproject, indices = minimal_indices)
#print(missing_meta)
#out_coords_text(data_table = mfd_db_subproject, regions = regions, missing_meta = missing_meta)
```

```{r warning=F, echo=eval_debug, eval=T}
#samples_missing_coords <- missing_coords(mfd_db_subproject)

#if(length(samples_missing_coords)<N){
#  samples_on_map(data_table = mfd_db_subproject, samples_out = coords_out(regions_map = regions, data_table = mfd_db_subproject))
#}
```

## Output

### Write email
```{r warning=F, echo=eval_debug, eval=T}
if(class(missing_meta)=="data.frame"){
  tmp <- summarise_missing_metadata(missing_meta) 
  dir.create(file.path(paste0(mails_01.path, "/"), pid), showWarnings = FALSE)
  dir.create(file.path(paste0(reformat.metadata.path, "/"), pid), showWarnings = FALSE)
  print_email(fname=paste0(mails_01.path, "/", pid, "/mail.txt"), project_name = pnm, receivers = peo, requested_indices = minimal_indices)
}
```

### Write mapping
```{r echo=eval_debug, message=F, warning=F, error=F}
if(exists("mapping.project")){
  writexl::write_xlsx(mapping.project, paste0(reformat.metadata.path, "/", pid, "/", pid, "_mapping.xlsx"))
}
```

### Write table to be completed
```{r echo=eval_debug, message=F, warning=F, error=F}
if(exists("mapping.project")&class(missing_meta)=="data.frame"){
  print_incomplete_entries(data_table = mfd_db_subproject,
                         missing_indices = missing_meta$fieldsample_barcode,
                         mapping = mapping.project,
                         fname = paste0(mails_01.path, "/", pid, "/table_to_fill.xlsx"),
                         minimal_indices = minimal_indices,
                         project_name = pnm,
                         minimal_indices_explanation = minimal_indices_explanation)
} else if(class(missing_meta)=="data.frame") {
  print_incomplete_entries(data_table = mfd_db_subproject,
                         missing_indices = missing_meta$fieldsample_barcode,
                         fname = paste0(mails_01.path, "/", pid, "/table_to_fill.xlsx"),
                         minimal_indices = minimal_indices,
                         project_name = pnm,
                         minimal_indices_explanation = minimal_indices_explanation)
}
```

### Write minimal metadata
```{r echo=eval_debug, message=F, warning=F, error=F}
dir.create(file.path(paste0(reformat.metadata.path, "/"), pid), showWarnings = FALSE)
writexl::write_xlsx(mfd_db_subproject, paste0(reformat.metadata.path, "/", pid, "/", pid, "_minimal_metadata.xlsx"))
```

### Write project metadata map
```{r echo=eval_debug, message=F, warning=F, error=F}
metadata.map <- data.frame(name=c(), path=c(), description=c())
metadata.map <- rbind(metadata.map, data.frame(name=c("main"), path=paste0(pid, "/", pid, "_minimal_metadata.xlsx"),
                                               description=c("minimal metadata")))
writexl::write_xlsx(metadata.map, paste0(reformat.metadata.path, "/", pid, "/", pid, "_metadata_summary.xlsx"))

rm(pid, pnm, des, ext, peo, res, com, mfd_db_subproject, N, missing_meta, samples_missing_coords, mapping.project)
```
